// check genscript in root for generating scopes

export const apiScopes = {
    "analytics:read:extensions": "View analytics data for the Twitch Extensions owned by the authenticated account.\n\nAPI\nGet Extension Analytics",
    "analytics:read:games": "View analytics data for the games owned by the authenticated account.\n\nAPI\nGet Game Analytics",
    "bits:read": "View Bits information for a channel.\n\nAPI\nGet Bits Leaderboard\n\nEventSub\nChannel Bits Use\nChannel Cheer",
    "channel:bot": "Joins your channel’s chatroom as a bot user, and perform chat-related actions as that user.\n\nAPI\nSend Chat Message\n\nEventSub\nChannel Chat Clear\nChannel Chat Clear User Messages\nChannel Chat Message\nChannel Chat Message Delete\nChannel Chat Notification\nChannel Chat Settings Update",
    "channel:manage:ads": "Manage ads schedule on a channel.\n\nAPI\nSnooze Next Ad",
    "channel:read:ads": "Read the ads schedule and details on your channel.\n\nAPI\nGet Ad Schedule\n\nEventSub\nChannel Ad Break Begin",
    "channel:manage:broadcast": "Manage a channel’s broadcast configuration, including updating channel configuration and managing stream markers and stream tags.\n\nAPI\nModify Channel Information\nCreate Stream Marker\nReplace Stream Tags",
    "channel:read:charity": "Read charity campaign details and user donations on your channel.\n\nAPI\nGet Charity Campaign\nGet Charity Campaign Donations\n\nEventSub\nCharity Donation\nCharity Campaign Start\nCharity Campaign Progress\nCharity Campaign Stop",
    "channel:manage:clips": "Manage Clips for a channel.\n\nAPI\nGet Clips Download",
    "channel:edit:commercial": "Run commercials on a channel.\n\nAPI\nStart Commercial",
    "channel:read:editors": "View a list of users with the editor role for a channel.\n\nAPI\nGet Channel Editors",
    "channel:manage:extensions": "Manage a channel’s Extension configuration, including activating Extensions.\n\nAPI\nGet User Active Extensions\nUpdate User Extensions",
    "channel:read:goals": "View Creator Goals for a channel.\n\nAPI\nGet Creator Goals\n\nEventSub\nGoal Begin\nGoal Progress\nGoal End",
    "channel:read:guest_star": "Read Guest Star details for your channel.\n\nAPI\nGet Channel Guest Star Settings\nGet Guest Star Session\nGet Guest Star Invites\n\nEventSub\nChannel Guest Star Session Begin\nChannel Guest Star Session End\nChannel Guest Star Guest Update\nChannel Guest Star Settings Update",
    "channel:manage:guest_star": "Manage Guest Star for your channel.\n\nAPI\nUpdate Channel Guest Star Settings\nCreate Guest Star Session\nEnd Guest Star Session\nSend Guest Star Invite\nDelete Guest Star Invite\nAssign Guest Star Slot\nUpdate Guest Star Slot\nDelete Guest Star Slot\nUpdate Guest Star Slot Settings\n\nEventSub\nChannel Guest Star Session Begin\nChannel Guest Star Session End\nChannel Guest Star Guest Update\nChannel Guest Star Settings Update",
    "channel:read:hype_train": "View Hype Train information for a channel.\n\nAPI\nGet Hype Train Events\n\nEventSub\nHype Train Begin\nHype Train Progress\nHype Train End",
    "channel:manage:moderators": "Add or remove the moderator role from users in your channel.\n\nAPI\nAdd Channel Moderator\nRemove Channel Moderator\nGet Moderators",
    "channel:read:polls": "View a channel’s polls.\n\nAPI\nGet Polls\n\nEventSub\nChannel Poll Begin\nChannel Poll Progress\nChannel Poll End",
    "channel:manage:polls": "Manage a channel’s polls.\n\nAPI\nGet Polls\nCreate Poll\nEnd Poll\n\nEventSub\nChannel Poll Begin\nChannel Poll Progress\nChannel Poll End",
    "channel:read:predictions": "View a channel’s Channel Points Predictions.\n\nAPI\nGet Channel Points Predictions\n\nEventSub\nChannel Prediction Begin\nChannel Prediction Progress\nChannel Prediction Lock\nChannel Prediction End",
    "channel:manage:predictions": "Manage of channel’s Channel Points Predictions\n\nAPI\nGet Channel Points Predictions\nCreate Channel Points Prediction\nEnd Channel Points Prediction\n\nEventSub\nChannel Prediction Begin\nChannel Prediction Progress\nChannel Prediction Lock\nChannel Prediction End",
    "channel:manage:raids": "Manage a channel raiding another channel.\n\nAPI\nStart a raid\nCancel a raid",
    "channel:read:redemptions": "View Channel Points custom rewards and their redemptions on a channel.\n\nAPI\nGet Custom Reward\nGet Custom Reward Redemption\n\nEventSub\nChannel Points Automatic Reward Redemption\nChannel Points Automatic Reward Redemption v2\nChannel Points Custom Reward Add\nChannel Points Custom Reward Update\nChannel Points Custom Reward Remove\nChannel Points Custom Reward Redemption Add\nChannel Points Custom Reward Redemption Update",
    "channel:manage:redemptions": "Manage Channel Points custom rewards and their redemptions on a channel.\n\nAPI\nGet Custom Reward\nGet Custom Reward Redemption\nCreate Custom Rewards\nDelete Custom Reward\nUpdate Custom Reward\nUpdate Redemption Status\n\nEventSub\nChannel Points Automatic Reward Redemption\nChannel Points Custom Reward Add\nChannel Points Custom Reward Update\nChannel Points Custom Reward Remove\nChannel Points Custom Reward Redemption Add\nChannel Points Custom Reward Redemption Update",
    "channel:manage:schedule": "Manage a channel’s stream schedule.\n\nAPI\nUpdate Channel Stream Schedule\nCreate Channel Stream Schedule Segment\nUpdate Channel Stream Schedule Segment\nDelete Channel Stream Schedule Segment",
    "channel:read:stream_key": "View an authorized user’s stream key.\n\nAPI\nGet Stream Key",
    "channel:read:subscriptions": "View a list of all subscribers to a channel and check if a user is subscribed to a channel.\n\nAPI\nGet Broadcaster Subscriptions\n\nEventSub\nChannel Subscribe\nChannel Subscription End\nChannel Subscription Gift\nChannel Subscription Message",
    "channel:manage:videos": "Manage a channel’s videos, including deleting videos.\n\nAPI\nDelete Videos",
    "channel:read:vips": "Read the list of VIPs in your channel.\n\nAPI\nGet VIPs\n\nEventSub\nChannel VIP Add\nChannel VIP Remove",
    "channel:manage:vips": "Add or remove the VIP role from users in your channel.\n\nAPI\nGet VIPs\nAdd Channel VIP\nRemove Channel VIP\n\nEventSub\nChannel VIP Add\nChannel VIP Remove",
    "channel:moderate": "Perform moderation actions in a channel.\n\nEventSub\nChannel Ban\nChannel Unban",
    "clips:edit": "Manage Clips for a channel.\n\nAPI\nCreate Clip",
    "editor:manage:clips": "Manage Clips as an editor.\n\nAPI\nGet Clips Download",
    "moderation:read": "View a channel’s moderation data including Moderators, Bans, Timeouts, and Automod settings.\n\nAPI\nCheck AutoMod Status\nGet Banned Users\nGet Moderators\n\nEventSub\nChannel Moderator Add\nChannel Moderator Remove",
    "moderator:manage:announcements": "Send announcements in channels where you have the moderator role.\n\nAPI\nSend Chat Announcement",
    "moderator:manage:automod": "Manage messages held for review by AutoMod in channels where you are a moderator.\n\nAPI\nManage Held AutoMod Messages\n\nEventSub\nAutoMod Message Hold\nAutoMod Message Hold v2\nAutoMod Message Update\nAutoMod Message Update v2\nAutoMod Terms Update",
    "moderator:read:automod_settings": "View a broadcaster’s AutoMod settings.\n\nAPI\nGet AutoMod Settings\n\nEventSub\nAutoMod Settings Update",
    "moderator:manage:automod_settings": "Manage a broadcaster’s AutoMod settings.\n\nAPI\nUpdate AutoMod Settings",
    "moderator:read:banned_users": "Read the list of bans or unbans in channels where you have the moderator role.\n\nEventSub\nChannel Moderate\nChannel Moderate v2",
    "moderator:manage:banned_users": "Ban and unban users.\n\nAPI\nGet Banned Users\nBan User\nUnban User\n\nEventSub\nChannel Moderate\nChannel Moderate v2",
    "moderator:read:blocked_terms": "View a broadcaster’s list of blocked terms.\n\nAPI\nGet Blocked Terms\n\nEventSub\nChannel Moderate",
    "moderator:read:chat_messages": "Read deleted chat messages in channels where you have the moderator role.\n\nEventSub\nChannel Moderate",
    "moderator:manage:blocked_terms": "Manage a broadcaster’s list of blocked terms.\n\nAPI\nGet Blocked Terms\nAdd Blocked Term\nRemove Blocked Term\n\nEventSub\nChannel Moderate",
    "moderator:manage:chat_messages": "Delete chat messages in channels where you have the moderator role\n\nAPI\nDelete Chat Messages\n\nEventSub\nChannel Moderate",
    "moderator:read:chat_settings": "View a broadcaster’s chat room settings.\n\nAPI\nGet Chat Settings\n\nEventSub\nChannel Moderate",
    "moderator:manage:chat_settings": "Manage a broadcaster’s chat room settings.\n\nAPI\nUpdate Chat Settings\n\nEventSub\nChannel Moderate",
    "moderator:read:chatters": "View the chatters in a broadcaster’s chat room.\n\nAPI\nGet Chatters",
    "moderator:read:followers": "Read the followers of a broadcaster.\n\nAPI\nGet Channel Followers\n\nEventSub\nChannel Follow",
    "moderator:read:guest_star": "Read Guest Star details for channels where you are a Guest Star moderator.\n\nAPI\nGet Channel Guest Star Settings\nGet Guest Star Session\nGet Guest Star Invites\n\nEventSub\nChannel Guest Star Session Begin\nChannel Guest Star Session End\nChannel Guest Star Guest Update\nChannel Guest Star Settings Update",
    "moderator:manage:guest_star": "Manage Guest Star for channels where you are a Guest Star moderator.\n\nAPI\nSend Guest Star Invite\nDelete Guest Star Invite\nAssign Guest Star Slot\nUpdate Guest Star Slot\nDelete Guest Star Slot\nUpdate Guest Star Slot Settings\n\nEventSub\nChannel Guest Star Session Begin\nChannel Guest Star Session End\nChannel Guest Star Guest Update\nChannel Guest Star Settings Update",
    "moderator:read:moderators": "Read the list of moderators in channels where you have the moderator role.\n\nEventSub\nChannel Moderate\nChannel Moderate v2",
    "moderator:read:shield_mode": "View a broadcaster’s Shield Mode status.\n\nAPI\nGet Shield Mode Status\n\nEventSub\nShield Mode Begin\nShield Mode End",
    "moderator:manage:shield_mode": "Manage a broadcaster’s Shield Mode status.\n\nAPI\nUpdate Shield Mode Status\n\nEventSub\nShield Mode Begin\nShield Mode End",
    "moderator:read:shoutouts": "View a broadcaster’s shoutouts.\n\nEventSub\nShoutout Create\nShoutout Received",
    "moderator:manage:shoutouts": "Manage a broadcaster’s shoutouts.\n\nAPI\nSend a Shoutout\n\nEventSub\nShoutout Create\nShoutout Received",
    "moderator:read:suspicious_users": "Read chat messages from suspicious users and see users flagged as suspicious in channels where you have the moderator role.\n\nEventSub\nChannel Suspicious User Message\nChannel Suspicious User Update",
    "moderator:read:unban_requests": "View a broadcaster’s unban requests.\n\nAPI\nGet Unban Requests\n\nEventSub\nChannel Unban Request Create\nChannel Unban Request Resolve\nChannel Moderate",
    "moderator:manage:unban_requests": "Manage a broadcaster’s unban requests.\n\nAPI\nResolve Unban Requests\n\nEventSub\nChannel Unban Request Create\nChannel Unban Request Resolve\nChannel Moderate",
    "moderator:read:vips": "Read the list of VIPs in channels where you have the moderator role.\n\nEventSub\nChannel Moderate\nChannel Moderate v2",
    "moderator:read:warnings": "Read warnings in channels where you have the moderator role.\n\nEventSub\nChannel Moderate v2\nChannel Warning Acknowledge\nChannel Warning Send",
    "moderator:manage:warnings": "Warn users in channels where you have the moderator role.\n\nAPI\nWarn Chat User\n\nEventSub\nChannel Moderate v2\nChannel Warning Acknowledge\nChannel Warning Send",
    "user:bot": "Join a specified chat channel as your user and appear as a bot, and perform chat-related actions as your user.\n\nAPI\nSend Chat Message\n\nEventSub\nChannel Chat Clear\nChannel Chat Clear User Messages\nChannel Chat Message\nChannel Chat Message Delete\nChannel Chat Notification\nChannel Chat Settings Update\nChannel Chat User Message Hold\nChannel Chat User Message Update",
    "user:edit": "Manage a user object.\n\nAPI\nUpdate User",
    "user:edit:broadcast": "View and edit a user’s broadcasting configuration, including Extension configurations.\n\nAPI\nGet User Extensions\nGet User Active Extensions\nUpdate User Extensions",
    "user:read:blocked_users": "View the block list of a user.\n\nAPI\nGet User Block List",
    "user:manage:blocked_users": "Manage the block list of a user.\n\nAPI\nBlock User\nUnblock User",
    "user:read:broadcast": "View a user’s broadcasting configuration, including Extension configurations.\n\nAPI\nGet Stream Markers\nGet User Extensions\nGet User Active Extensions",
    "user:read:chat": "Receive chatroom messages and informational notifications relating to a channel’s chatroom.\n\nEventSub\nChannel Chat Clear\nChannel Chat Clear User Messages\nChannel Chat Message\nChannel Chat Message Delete\nChannel Chat Notification\nChannel Chat Settings Update\nChannel Chat User Message Hold\nChannel Chat User Message Update",
    "user:manage:chat_color": "Update the color used for the user’s name in chat.\n\nAPI\nUpdate User Chat Color",
    "user:read:email": "View a user’s email address.\n\nAPI\nGet Users (optional)\nUpdate User (optional)\n\nEventSub\nUser Update (optional)",
    "user:read:emotes": "View emotes available to a user\n\nAPI\nGet User Emotes",
    "user:read:follows": "View the list of channels a user follows.\n\nAPI\nGet Followed Channels\nGet Followed Streams",
    "user:read:moderated_channels": "Read the list of channels you have moderator privileges in.\n\nAPI\nGet Moderated Channels",
    "user:read:subscriptions": "View if an authorized user is subscribed to specific channels.\n\nAPI\nCheck User Subscription",
    "user:read:whispers": "Receive whispers sent to your user.\n\nEventSub\nWhisper Received",
    "user:manage:whispers": "Receive whispers sent to your user, and send whispers on your user’s behalf.\n\nAPI\nSend Whisper\n\nEventSub\nWhisper Received",
    "user:write:chat": "Send chat messages to a chatroom.\n\nAPI\nSend Chat Message"
}

export const chatScopes = {
  "chat:edit": "Send live stream chat messages using an IRC connection.",
  "chat:read": "View live stream chat messages using an IRC connection.",
}